---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 1521, host: 1521}]
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: CentOS-6.5-oracledb-11.2.0.4
    driver:
      box: CentOS-6.5-oracledb-11.2.0.4

suites:
  - name: default
    run_list:
      - recipe[oracle::default]
    attributes:
